// AUTHOR - TYPES
// =============================================================================
export const FETCH_RELATED_ARTICLES_FROM_ID_REQUEST = 'FETCH_RELATED_ARTICLES_FROM_ID_REQUEST';
export const FETCH_RELATED_ARTICLES_FROM_ID_SUCCESS = 'FETCH_RELATED_ARTICLES_FROM_ID_SUCCESS';
export const FETCH_RELATED_ARTICLES_FROM_ID_FAILURE = 'FETCH_RELATED_ARTICLES_FROM_ID_FAILURE';
