// PREFERENCE - TYPES
// =============================================================================

export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST'
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_FAILURE = 'GET_FAVORITES_FAILURE'

export const SET_FAVORITES_REQUEST = 'SET_FAVORITES_REQUEST'
export const SET_FAVORITES_SUCCESS = 'SET_FAVORITES_SUCCESS'
export const SET_FAVORITES_FAILURE = 'SET_FAVORITES_FAILURE'

export const DELETE_FAVORITES_REQUEST = 'DELETE_FAVORITES_REQUEST'
export const DELETE_FAVORITES_SUCCESS = 'DELETE_FAVORITES_SUCCESS'
export const DELETE_FAVORITES_FAILURE = 'DELETE_FAVORITES_FAILURE'
