// PREFERENCE - TYPES
// =============================================================================
export const SET_PREFERENCE_REQUEST = 'SET_PREFERENCE_REQUEST';
export const SET_PREFERENCE_LANGUAGE = 'SET_PREFERENCE_LANGUAGE';
export const SET_PREFERENCE_FEED_TYPE = 'SET_PREFERENCE_FEED_TYPE';
export const SET_PREFERENCE_CITIES = 'SET_PREFERENCE_CITIES';
export const SET_PREFERENCE_INTERESTS = 'SET_PREFERENCE_INTERESTS';
export const SET_PREFERENCE_DONE = 'SET_PREFERENCE_DONE';

export const SAVE_PREFERENCES_REQUEST = 'SAVE_PREFERENCES_REQUEST';
export const SAVE_PREFERENCES_SUCCESS = 'SAVE_PREFERENCES_SUCCESS';
export const SAVE_PREFERENCES_FAILURE = 'SAVE_PREFERENCES_FAILURE';
